educates/educates-training-platform

client-programs/pkg/cmd/cluster_portal_create_cmd.go, client-programs/pkg/cmd/cluster_workshop_deploy_cmd.go
Addresses https://github.com/vmware-tanzu-labs/educates-training-platform/issues/93
=> Change default capacity limits for portal/workshops when using CLI.

client-programs/pkg/cmd/workshop_publish_cmd.go
Fixes: https://github.com/vmware-tanzu-labs/educates-training-platform/issues/102
=> Don't deploy local registry automatically when publishing workshop.

client-programs/pkg/cmd/docker_workshop_deploy_cmd.go
Fixes: https://github.com/vmware-tanzu-labs/educates-training-platform/issues/105
=> Set platform architecture variable when deploying workshop to local docker.

client-programs/pkg/cmd/cluster_workshop_serve_cmd.go
Fixes: https://github.com/vmware-tanzu-labs/educates-training-platform/issues/110
=> Ensure local config directory is created if doesn't exist.

carvel-packages/training-platform/bundle/config/11-session-manager/07-daemonsets.yaml
Fixes: https://github.com/vmware-tanzu-labs/educates-training-platform/issues/108
=> Allow image puller to be disabled by setting image list to empty.

carvel-packages/training-platform/bundle/config/11-session-manager/01-clusterroles.yaml
Fixes: https://github.com/vmware-tanzu-labs/educates-training-platform/issues/122
=> Missing finalizers RBAC required for OpenShift.

client-programs/pkg/cmd/cluster_workshop_serve_cmd.go
Fixes: https://github.com/vmware-tanzu-labs/educates-training-platform/issues/121
=> Change default loopback hostname so uses cluster domain variable.

client-programs/pkg/cmd/admin_cluster_create_cmd.go
Fixes: https://github.com/vmware-tanzu-labs/educates-training-platform/issues/136
=> Use specific kapp-controller version but allow override.

workshop-images/conda-environment/Dockerfile
Avoids error:
```
Error while loading conda entry point: conda-libmamba-solver (/opt/conda/lib/python3.11/site-packages/libmambapy/../../../libmamba.so.2: undefined symbol: solver_ruleinfo2str, version SOLV_1.0)
```
=> Update conda versions to avoid resolver build bug.

developer-docs/release-procedures.md
closes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/268
=> Fix format of example pre-release tag versions.

project-docs/getting-started/creating-a-workshop.md, project-docs/release-notes/version-2.7.0.md, project-docs/workshop-content/workshop-instructions.md, workshop-images/base-environment/opt/renderer/src/frontend/scripts/educates.ts
closes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/99
=> Allow $HOME/ reference in editor clickable actions.

carvel-packages/training-platform/bundle/config/06-secrets.yaml, project-docs/release-notes/version-2.7.0.md
Removes the type `kubernetes.io/tls` from the secret created for CA when configuration used an embedded cert.
Closes #301
=> Fixes secret for embedded CA

secrets-manager/main.py, session-manager/main.py, training-portal/src/project/apps/workshops/manager/operator.py, tunnel-manager/main.py
Further changes related to https://github.com/vmware-tanzu-labs/educates-training-platform/issues/202
=> Add kopf client timeout and adjust server timeout to 5 minutes.

project-docs/custom-resources/workshop-definition.md
In docs' section about enabling slides, configuration is wrongly stating that `enabled: false` is the way to enable slides while the right way is `enabled: true`
=> Fix incorrect enabled value for slides

.github/workflows/build-and-publish-images.yaml
Under GitHub actions, macos-latest runner has been changed from AMD64 macos-12 to ARM64 macos-14. Pin runner to old AMR64 version for now and revisit how to cross compile to AMD64 from ARM64 later. Need to double check DNS resolver usage when revisit direction of cross compilation.
GitHub actions announcement and runner details:
* https://github.blog/changelog/2024-04-01-macos-14-sonoma-is-generally-available-and-the-latest-macos-runner-image/
* https://github.com/actions/runner-images?tab=readme-ov-file#available-images
=> Pin macos version under GitHub actions so uses Intel runner.

project-docs/release-notes/version-2.7.1.md, training-portal/src/project/settings.py
Change fixed `www` prefix for `google-analytics.com` and `googletagmanager.com` into wildcard.
This is related to [this Slack thread](https://kubernetes.slack.com/archives/C05UWT4SKRV/p1716365009570249), I opted for changing the `www.googletagmanager.com` directive in addition to the `google-analytics.com` directive that has already proven faulty, as I thought there might occur similar problems down the road for `googletagmanager.com` at some point.
I will build the training-portal image and test it, will report back if this resolves the issue.
Fixes #377
=> Update CSP directives targeting Google Analytics

project-docs/release-notes/version-2.7.1.md, session-manager/handlers/workshopallocation.py
fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/343
=> Increase timeout for workshop session registration.

carvel-packages/training-platform/bundle/config/00-values.yaml, carvel-packages/training-platform/config/images.yaml, project-docs/release-notes/version-2.7.1.md, session-manager/handlers/application_vcluster.py, session-manager/handlers/operator_config.py, workshop-images/base-environment/Dockerfile, workshop-images/base-environment/opt/eduk8s/etc/setup.d/01-kubernetes.sh, workshop-images/base-environment/opt/kubernetes/bin/kubectl
Updated vcluster to 0.18.1. Note that not gone to 0.19.x as that version changes the architecture of how vcluster is deployed. Updated kubectl versions and vcluster to support 1.27-1.30, defaulting to 1.29.
=> Fix vcluster DNS lookup and update kubectl versions.

Makefile, client-programs/pkg/cmd/admin_cluster_create_cmd.go, client-programs/pkg/registry/registry.go
This changes adds more qualification to duplicate messages when linking cluster to local registry. Fixes format of cluster-create command and adds `ns delete` to makefile target
Closes #409 
Closes #410 
Closes #411
=> Fixing duplicate log messages, cmd output and makefile

carvel-packages/installer/bundle/config/ytt/_ytt_lib/config/save-config-overlay.yaml, carvel-packages/installer/bundle/config/ytt/config.yaml
ClusterPackages config is saved into the cluster in `educates-config` configmap in `educates-config` namespace.
ClusterInfrastructure configuration is not saved, it's only the rendered configuration for the packages. 
Closes #417
=> Saving clusterPackages config into the cluster

Makefile, carvel-packages/installer/bundle/config/ytt/_ytt_lib/infrastructure/custom/educates.lib.yaml, carvel-packages/installer/bundle/config/ytt/_ytt_lib/infrastructure/eks/educates.lib.yaml, carvel-packages/installer/bundle/config/ytt/_ytt_lib/infrastructure/gke/educates.lib.yaml, carvel-packages/installer/bundle/config/ytt/_ytt_lib/infrastructure/kind/educates.lib.yaml, carvel-packages/installer/bundle/config/ytt/_ytt_lib/infrastructure/vcluster/educates.lib.yaml, client-programs/pkg/cmd/admin_cluster_cmd_group.go, client-programs/pkg/cmd/admin_cluster_create_cmd.go, client-programs/pkg/cmd/admin_config_view_cmd.go, client-programs/pkg/cmd/admin_platform_cmd_group.go, client-programs/pkg/cmd/admin_platform_delete_cmd.go, client-programs/pkg/cmd/admin_platform_deploy_cmd.go, client-programs/pkg/cmd/admin_platform_install_cmd.go, client-programs/pkg/cmd/admin_resolver_deploy_cmd.go, client-programs/pkg/cmd/educates_cmd_group.go, client-programs/pkg/config/installationconfig.go, developer-docs/build-instructions.md
Portal credentials/clients settings not passed through.
fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/421
fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/422
Change naming for CLI platform deployment commands/aliases, as well as makefile targets when building locally.
closes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/424
Add distinct platform delete command.
closes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/425
=> Updates to platform deployment using CLI.

client-programs/pkg/installer/installer.go
When using `--version=latest` it'll skip image resolution. This is because `--version=latest` is a hack to use local image registry for deployment of images, and we don't want in this scenarios to have deployments using the SHA of the images but rather a tag, so that it'll always update to the latest version available in the registry.
=> Version=latest also skips image resolution

carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/educates/11-session-manager/01-crds-workshop.yaml, project-docs/release-notes/version-3.0.0.md
fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/442
=> Missing changeOrigin property for ingresses in Workshop CRD.

client-programs/pkg/cmd/admin_cluster_create_cmd.go
fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/452
=> Must still consume output when not verbose flag else image pull doesn't run.

.github/workflows/build-and-publish-images.yaml
Upgraded github actions in our workflow to use versions with node-20 and not node-16 which is no longer supported.
Closes #387 
Squash when merging.
=> Actions node 20

client-programs/pkg/cmd/local_cluster_create_cmd.go, client-programs/pkg/cmd/local_registry_deploy_cmd.go, client-programs/pkg/registry/registry.go
Fixes #162 
Fixes #163 
`educates local registry create` and `educates admin cluster create` now have the option to provide a bindIP for the registry.
This can be an IP or a name, but Docker needs to be able to bind to that IP given the networking configuration, so mostly only works with 127.0.0.1 which is the default or 0.0.0.0.  Any other IP, or domain that resolves to an IP, might not work if Docker
=> Adding bind-ip to registry

client-programs/pkg/templates/files/hugo/.gitignore, client-programs/pkg/templates/internal.go
Fixes #429 
Adding a .gitignore file to the top of the template (Only for hugo since classic don't create these files anyways) works for when the workshop directory is top level git repo or when it's included in multiworkshop repo.
=> Adding .gitignore to workshop templates

carvel-packages/installer/bundle/config/ytt/_ytt_lib/infrastructure/eks/10-defaults.yaml, carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/certs/values-schema.yaml, carvel-packages/installer/bundle/config/ytt/values-schema.yaml, carvel-packages/installer/scenarios/eks/test-eks-scenario-01/values.yaml, carvel-packages/installer/scenarios/eks/test-eks-scenario-01b/description.md, carvel-packages/installer/scenarios/eks/test-eks-scenario-01b/expected.yaml, carvel-packages/installer/scenarios/eks/test-eks-scenario-01b/values.yaml, carvel-packages/installer/scenarios/eks/test-eks-scenario-02/expected.yaml, carvel-packages/installer/scenarios/eks/test-eks-scenario-02/values.yaml, carvel-packages/installer/scenarios/eks/test-eks-scenario-03/expected.yaml
Closes #496 
We have added an additional configuration to the clusterInfrastructure.aws schema.
```
clusterInfrastructure:
aws:
route53:
hostedZone: "my-zone"
```
If this is not provided, the same as `clusterIngress.domain` will be selected.
Added a test scenario.
=> Some EKS provider updates

carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/contour/overlays/overlay-contour.yaml, carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/contour/rules.star, carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/contour/values-schema.yaml, carvel-packages/installer/scenarios/kind/test-kind-scenario-13/description.md, carvel-packages/installer/scenarios/kind/test-kind-scenario-13/expected.yaml, carvel-packages/installer/scenarios/kind/test-kind-scenario-13/values.yaml, carvel-packages/installer/scenarios/test-scenarios.sh
Fixes #510 
Since there's a problem when calling ytt with default schema and values in a `data/values` file as mentioned in [this thread](https://kubernetes.slack.com/archives/CH8KCCKA5/p1721036012274939), we extracted the defaults from the schema into a function of the overlay.
=> Fixing default HTTP versions in contour

carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/educates/11-session-manager/01-crds-workshopallocation.yaml, carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/educates/11-session-manager/01-crds-workshopsession.yaml, project-docs/release-notes/version-3.0.0.md, session-manager/handlers/workshopsession.py, training-portal/src/project/apps/workshops/manager/sessions.py, training-portal/src/project/apps/workshops/views/environment.py, training-portal/src/project/apps/workshops/views/session.py
Fix incorrect status being left on workshop session.
fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/515
Fix internal error when try to acquire session not created via REST API.
fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/503
As well as fixing linked issues, add session user against status of `WorkshopSession`, and in `WorkshopAllocation`, to allow easier tracking of malicious users, and make it easier to determine when user has an existing workshop session when a workshop request is being handled by a lookup service.
=> Record session user when allocating session.

carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/external-dns/overlays/defaults.star, carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/external-dns/values-schema.yaml, client-programs/pkg/config/installationconfig.go
This changes the behaviour of external-dns with relation to Route53, as it changed upstream in version [0.13.6](https://github.com/kubernetes-sigs/external-dns/releases/tag/v0.13.6) (https://github.com/kubernetes-sigs/external-dns/pull/3695)
This PR will:
- Only apply to services as we do set an annotation on the envoy service for wildcard domain, and that's the only one needed
- Add `--aws-zone-match-parent` to support back match parents as fixed by https://github.com/kubernetes-sigs/external-dns/pull/4236 in [0.14.1](https://github.com/kubernetes-sigs/external-dns/releases/tag/v0.14.1)
- Changed `--policy` to `sync` so that txt and CNAMEs are deleted on uninstall. Previously we had `upsert-only` which left the records there.
Fixes #535
=> Fixing external-dns config for route53

carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/external-dns/values-schema.yaml
Reverts setting for policy as described in https://github.com/vmware-tanzu-labs/educates-training-platform/issues/545
=> Revert to upsert-only for extenal-dns policy.

lookup-service/service/routes/workshops.py, project-docs/release-notes/version-3.0.1.md
This change allows an existing workshop session to be found by the lookup service even where label selectors for a tenant were changed such that existing cluster/portal was no longer accessing to the tenant.
=> Lookup existing session.

carvel-packages/installer/bundle/config/ytt/_ytt_lib/infrastructure/eks/10-default-settings-for-provider.yaml, carvel-packages/installer/bundle/config/ytt/_ytt_lib/infrastructure/gke/10-default-settings-for-provider.yaml
Adding a unique `txt_owner_id` allows for no collision of records in Route53 hostedZones so that sync can be used.
As in Route53 we have a configuration of `--aws-zone-match-parent` if there's multiple hostedZones for toplevel domains, record will be created in the first one found as traversing the structure from longer to shorter.
e.g. if there's a hosted zone for `labs.example.com` and another one for `example.com` if we create a cluster with name `cluster.labs.example.com` the record will be created in `labs.example.com`. If this zone didn't exist, it would use `example.com` zone. If we want to explicitly create the record in any zone, we can use the config value `clusterInfrastructure.aws.route53.hostedZone` to define that external-dns should only create records there.
I have …
=> Sync external-dns hostedzone record changes

Makefile, assets-server/Dockerfile, workshop-images/jdk11-environment/Dockerfile, workshop-images/jdk17-environment/Dockerfile, workshop-images/jdk21-environment/Dockerfile, workshop-images/jdk21-environment/gradle.properties, workshop-images/jdk8-environment/Dockerfile
Updates for:
- JDK for all versions to the latests
- Maven all Java images to 3.9.9
- Gradle updated for JDK21 image to 8.8 (all others remain on 8.5)
- Added to makefile all target making of binaries and pushing of installer bundle
- Fixing casing warning on assets-server's Dockerfile
=> Updating maven, gradle and JDK versions and minor fixes

project-docs/release-notes/version-3.2.0.md, session-manager/handlers/application_git.py
fixes #652 
For now this makes git password same as general purpose services password. Had them different before so not sharing services password intended for internal cluster usage, outside of cluster if someone needed to push to git from outside of workshop container. Likelihood of workshop needing that is low and so risk of it being an issue is very small.
=> Fix git password uniqueness problem.

carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/cert-manager/overlays/overlay-modify-acmeresolver-reference.yaml, carvel-packages/installer/bundle/kbld/kbld-bundle.yaml, carvel-packages/installer/scenarios/custom/test-custom-scenario-4/description.md, carvel-packages/installer/scenarios/custom/test-custom-scenario-4/expected.yaml, carvel-packages/installer/scenarios/custom/test-custom-scenario-4/values.yaml, project-docs/release-notes/version-3.2.1.md
This fixes the ability to run disconnected installs as now the configuration and descriptors can have the resolved sha256 of every image referenced.
Fixes #605
=> Fixing resolution of images

carvel-packages/installer/bundle/config/ytt/_ytt_lib/config/save-config-overlay.yaml, carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/educates/06-secrets.yaml, carvel-packages/installer/bundle/kbld/kbld-bundle.yaml, client-programs/pkg/cmd/admin_platform_config_cmd.go, client-programs/pkg/installer/installer.go, secrets-manager/handlers/operator_config.py, session-manager/handlers/operator_config.py
Modified:
- Name of key in educates-config secret to `educates-operator-config.yaml` and provided as stringData
- Name of keys in educates-config configmap to `educates-original-config.yaml` and `educates-processed-values.yaml`
- CLI to use these new names for `educates admin platform values --from-cluster` and `educates admin platform config --from-cluster`
- Operator (secret-manager and session-manager) to use new key in educates-config secret
- kbld searchRules
- Removed unused code in `admin_platform_config_cmd.go`
This PR fixes a problem introduced in #672 which finally solves #605
=> Fixing problem generated by previous kbld fix

carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/educates/_ytt_lib/lookup-service/overlays.yaml/overlay-ingress.yaml
There was an error in the ytt overlay that as certName was defaulted to "", it was always adding the TLS section to lookup-service ingress. This is now fixed.
=> Fixing lookup ingress when insecure

client-programs/pkg/cmd/local_resolver_cmd_group.go, client-programs/pkg/cmd/local_resolver_update_cmd.go, client-programs/pkg/resolver/resolver.go, project-docs/release-notes/version-3.3.0.md
Adds a new command `educates local resolver update` that will generate and update the resolver configuration.
This command is useful to reload the resolver when using the local resolver and your local ip has changed.
Solves #689 
PS: We can review the name of action if you prefer `reload` or `refresh` rather than `update`
=> Local resolver reload

client-programs/pkg/diagnostics/diagnostics.go
The issue is that filepath.Ext() only returns the extension from the last dot, so for "diagnostics.tar.gz" it returns ".gz" not ".tar.gz". We update the implementation to properly check for `.tar.gz` suffix
Fixes #713
=> Fixing diagnostics check for .tar.gz
