client-programs/pkg/cmd/cluster_workshop_deploy_cmd.go

Fixes: https://github.com/vmware-tanzu-labs/educates-training-platform/issues/93

Set capacity as 0 if not provided and don't cap values.

---

client-programs/pkg/cmd/admin_cluster_create_cmd.go
client-programs/pkg/cmd/cluster_workshop_serve_cmd.go

Fixes: https://github.com/vmware-tanzu-labs/educates-training-platform/issues/111

Create a loopback service mapping to the cluster ingress router.

---

workshop-images/base-environment/opt/gateway/src/backend/modules/uploads.ts

Fixes: https://github.com/vmware-tanzu-labs/educates-training-platform/issues/109

Change temporary directory used for uploads.

---

workshop-images/base-environment/opt/eduk8s/bin/xdg-open
workshop-images/base-environment/opt/gateway/src/backend/modules/messages.ts
workshop-images/base-environment/opt/gateway/src/backend/modules/terminals.ts
workshop-images/base-environment/opt/gateway/src/backend/server.ts
workshop-images/base-environment/opt/gateway/src/frontend/scripts/educates.ts

Fixes: https://github.com/vmware-tanzu-labs/educates-training-platform/issues/101

Add API for triggering actions from terminal, with xdg-open support.

---

client-programs/pkg/cmd/cluster_portal_open_cmd.go
client-programs/pkg/cmd/cluster_workshop_deploy_cmd.go
client-programs/pkg/cmd/cluster_workshop_serve_cmd.go
client-programs/pkg/cmd/cluster_workshop_update_cmd.go
client-programs/pkg/cmd/workshop_publish_cmd.go

Fixes: https://github.com/vmware-tanzu-labs/educates-training-platform/issues/90

Add progress messages to CLI so know what is doing for common commands.

---

session-manager/handlers/workshopenvironment.py
session-manager/handlers/workshopsession.py

Fixes: https://github.com/vmware-tanzu-labs/educates-training-platform/issues/119

Add variables for workshop environment/session resource uids.

---

client-programs/pkg/cmd/cluster_workshop_request_cmd.go

Fixes: https://github.com/vmware-tanzu-labs/educates-training-platform/issues/128

Add user option for when requesting workshop using CLI to test REST API.

---

client-programs/pkg/cmd/cluster_workshop_request_cmd.go

Fixes: https://github.com/vmware-tanzu-labs/educates-training-platform/issues/100

Add request activation timeout and no browser option.

---

client-programs/pkg/cmd/cluster_workshop_request_cmd.go

Fixes: https://github.com/vmware-tanzu-labs/educates-training-platform/issues/132

Add way to override environment name when requesting workshop session using CLI.

---

session-manager/requirements.txt

Fixes: https://github.com/vmware-tanzu-labs/educates-training-platform/pull/134

Update cryptography version.

---

.github/workflows/build-and-publish-images.yaml

fixes: https://github.com/vmware-tanzu-labs/educates-training-platform/issues/156

Fix directory package files are placed for PR upon release.

---

.github/workflows/build-and-publish-images.yaml

fixes: https://github.com/vmware-tanzu-labs/educates-training-platform/issues/159

Don't create a PR for package files in a fork.

---

project-docs/requirements.in
project-docs/requirements.txt
training-portal/requirements.in
training-portal/requirements.txt

fixes: https://github.com/vmware-tanzu-labs/educates-training-platform/pull/158

Update urllib3 version due to CVE.

---

docker-extension/ui/package-lock.json
docker-extension/ui/package.json

fixes: https://github.com/vmware-tanzu-labs/educates-training-platform/security/dependabot/99

Update npm packages in docker-extension due to CVEs.

---

developer-docs/release-procedures.md
project-docs/workshop-content/building-an-image.md
project-docs/workshop-content/working-on-content.md
project-docs/workshop-content/workshop-instructions.md

fixes: https://github.com/vmware-tanzu-labs/educates-training-platform/issues/183
fixes: https://github.com/vmware-tanzu-labs/educates-training-platform/issues/177
fixes: https://github.com/vmware-tanzu-labs/educates-training-platform/issues/168

Ad-doc documentation updates.

---

docker-extension/package-lock.json
docker-extension/ui/package-lock.json
project-docs/requirements.in
project-docs/requirements.txt
training-portal/requirements.in
training-portal/requirements.txt

closes: https://github.com/vmware-tanzu-labs/educates-training-platform/pull/195
closes: https://github.com/vmware-tanzu-labs/educates-training-platform/pull/198

Update package versions due to CVEs.

---

client-programs/go.mod
client-programs/go.sum
training-portal/requirements.in
workshop-images/base-environment/opt/gateway/package-lock.json
workshop-images/base-environment/opt/renderer/package-lock.json

closes https://github.com/vmware-tanzu-labs/educates-training-platform/pull/203
closes https://github.com/vmware-tanzu-labs/educates-training-platform/pull/205
closes https://github.com/vmware-tanzu-labs/educates-training-platform/pull/206
closes https://github.com/vmware-tanzu-labs/educates-training-platform/security/dependabot/109
closes https://github.com/vmware-tanzu-labs/educates-training-platform/security/dependabot/108
closes https://github.com/vmware-tanzu-labs/educates-training-platform/security/dependabot/107
closes https://github.com/vmware-tanzu-labs/educates-training-platform/security/dependabot/106

Updates for CVE reports.

---

project-docs/release-notes/version-2.7.0.md
project-docs/workshop-content/workshop-instructions.md
workshop-images/base-environment/opt/gateway/src/backend/modules/examiner.ts

fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/201

Ensure working directory set to home directory for examiner scripts.

---

project-docs/release-notes/version-2.7.0.md
project-docs/workshop-content/workshop-instructions.md
workshop-images/base-environment/opt/gateway/src/backend/views/workarea-panel-content.pug
workshop-images/base-environment/opt/gateway/src/frontend/scripts/educates.ts
workshop-images/base-environment/opt/renderer/src/frontend/scripts/educates.ts

closes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/196
closes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/197

Improvements to terminal focus.

---

workshop-images/base-environment/opt/gateway/package-lock.json
workshop-images/base-environment/opt/gateway/package.json

closes https://github.com/vmware-tanzu-labs/educates-training-platform/security/dependabot/112
closes https://github.com/vmware-tanzu-labs/educates-training-platform/pull/217

Update axios packages due to CVE.

---

secrets-manager/requirements.txt
session-manager/requirements.txt
training-portal/requirements.in
training-portal/requirements.txt
tunnel-manager/requirements.txt

closes https://github.com/vmware-tanzu-labs/educates-training-platform/security/dependabot/116
closes https://github.com/vmware-tanzu-labs/educates-training-platform/security/dependabot/115
closes https://github.com/vmware-tanzu-labs/educates-training-platform/security/dependabot/114
closes https://github.com/vmware-tanzu-labs/educates-training-platform/security/dependabot/113

Update aiohttp version due to CVE.

---

docker-extension/ui/package-lock.json
docker-extension/ui/package.json

closes https://github.com/vmware-tanzu-labs/educates-training-platform/security/dependabot/127
closes https://github.com/vmware-tanzu-labs/educates-training-platform/pull/234

Update packages due to CVE reports.

---

assets-server/Dockerfile
image-cache/Dockerfile
project-docs/getting-started/quick-start-guide.md
secrets-manager/Dockerfile
secrets-manager/requirements.txt
session-manager/Dockerfile
session-manager/handlers/daemons.py
session-manager/requirements.txt
tunnel-manager/Dockerfile
workshop-images/base-environment/Dockerfile

closes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/243

Update Fedora base image versions.

---

workshop-images/base-environment/Dockerfile
workshop-images/base-environment/opt/eduk8s/etc/setup.d/01-kubernetes.sh
workshop-images/base-environment/opt/kubernetes/bin/kubectl

closes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/68

Update bundled application versions, VS Code, kubectl, Carvel, k9s, etc.

---

project-docs/release-notes/version-2.7.0.md

Update with details of prior changes.

Add details to release notes.

---

project-docs/release-notes/version-2.7.0.md
workshop-images/base-environment/Dockerfile

closes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/225

Re-enable bracketed paste mode for bash shell environment.

---

workshop-images/base-environment/opt/gateway/package-lock.json

closes https://github.com/vmware-tanzu-labs/educates-training-platform/pull/257

Update follow-redirects package due tot CVE.

---

workshop-images/base-environment/opt/gateway/src/backend/modules/examiner.ts

closes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/264
closes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/236

Capture examiner script output in local log file.

---

.github/workflows/build-and-publish-images.yaml
Makefile
carvel-packages/training-platform/config/images.yaml
client-programs/pkg/cmd/docker_workshop_deploy_cmd.go
developer-docs/build-instructions.md
project-docs/custom-resources/workshop-definition.md
project-docs/getting-started/workshop-templates.md
project-docs/release-notes/version-2.0.0.md
project-docs/release-notes/version-2.7.0.md
project-docs/workshop-content/building-an-image.md
project-docs/workshop-migration/learning-center.md
session-manager/handlers/operator_config.py
workshop-images/jdk11-environment/Dockerfile
workshop-images/jdk17-environment/Dockerfile
workshop-images/jdk21-environment/Dockerfile
workshop-images/jdk21-environment/README.md
workshop-images/jdk21-environment/opt/eduk8s/etc/setup.d/11-java.sh
workshop-images/jdk8-environment/Dockerfile

closes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/255

Add JDK 21 workshop base image.

---

project-docs/custom-resources/training-portal.md
project-docs/release-notes/version-2.7.0.md
training-portal/src/project/apps/workshops/manager/environments.py

closes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/33

Fix portal workshop environment overrides update.

---

docker-extension/ui/package-lock.json
docker-extension/ui/package.json

closes https://github.com/vmware-tanzu-labs/educates-training-platform/security/dependabot/130
closes https://github.com/vmware-tanzu-labs/educates-training-platform/pull/273

Update vite package due to CVE.

---

workshop-images/base-environment/opt/renderer/src/frontend/scripts/educates.ts
workshop-images/base-environment/opt/renderer/src/frontend/styles/educates.css

closes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/274

Fix Bootstrap 5 styling issues.

---

workshop-images/base-environment/opt/gateway/src/backend/scripts/start-terminal

closes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/249

Add support for a global default terminal override script.

---

project-docs/release-notes/version-2.7.0.md
session-manager/handlers/kyverno_rules.py

closes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/281

Fix namespace selectors on Kyverno rules.

---

carvel-packages/training-platform/bundle/config/11-session-manager/01-crds-workshop.yaml
project-docs/custom-resources/workshop-definition.md
project-docs/release-notes/version-2.7.0.md
workshop-images/base-environment/opt/gateway/src/backend/modules/config.ts
workshop-images/base-environment/opt/gateway/src/backend/modules/proxy.ts

closes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/123
closes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/285

Workshop proxy changes.

---

workshop-images/base-environment/opt/gateway/src/backend/modules/access.ts

Fixes issue with error message not being logged.

Fix up logging for OAuth flow errors.

---

project-docs/release-notes/version-2.7.0.md
session-manager/handlers/operator_config.py

Fixes a typo in 2 lines of code.
Closes #299

Fixes embedded certs

---

session-manager/handlers/analytics.py
training-portal/src/project/apps/workshops/manager/analytics.py
training-portal/src/project/apps/workshops/views/session.py
training-portal/src/project/settings.py

Changes to make use of SQLite with many workshops more resilient.

Portal workshop handling.

---

training-portal/src/project/apps/workshops/manager/portal.py

Tries to address database commit lock issues with portal.

Move resource lock to parent function.

---

client-programs/go.mod
client-programs/go.sum
workshop-images/base-environment/opt/gateway/package-lock.json

closes https://github.com/vmware-tanzu-labs/educates-training-platform/pull/315
closes https://github.com/vmware-tanzu-labs/educates-training-platform/pull/316

CVE fixes.

---

project-docs/index.rst
project-docs/release-notes/version-2.7.1.md
secrets-manager/handlers/secretcopier_funcs.py
secrets-manager/handlers/secretimporter.py
secrets-manager/handlers/secretinjector_funcs.py

closes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/323

Handler terminating namespaces and errors when updating secrets.

---

project-docs/release-notes/version-2.7.1.md
workshop-images/base-environment/Dockerfile

Fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/352

Revert to using netcat instead of ncat for nc.

---

carvel-packages/training-platform/bundle/config/10-secrets-manager/07-deployments.yaml
carvel-packages/training-platform/bundle/config/11-session-manager/07-deployments.yaml
project-docs/release-notes/version-2.7.1.md
secrets-manager/main.py
session-manager/handlers/operator_config.py
session-manager/main.py

fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/359
fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/355
fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/361

Operator startup checks

---

project-docs/release-notes/version-2.7.1.md
project-docs/workshop-content/workshop-instructions.md
project-docs/workshop-migration/learning-center.md

fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/347 
fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/293

Docs updates.

---

project-docs/release-notes/version-2.7.1.md
session-manager/handlers/workshopsession.py
workshop-images/base-environment/opt/eduk8s/etc/profile.d/02-console.sh
workshop-images/base-environment/opt/eduk8s/sbin/start-container
workshop-images/base-environment/opt/eduk8s/sbin/start-gateway

fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/370

Workshop config overrides.

---

project-docs/release-notes/version-2.7.1.md
workshop-images/base-environment/opt/eduk8s/etc/templates/workshop-variables.yaml

fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/373

Workshop title in TOC was not being populated correctly.

---

training-portal/src/project/settings.py

fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/368

Remove duplicate config setting.

---

training-portal/src/project/static/styles/project.css

fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/324

Adjust padding around login form.

---

project-docs/getting-started/quick-start-guide.md

Documentation updates.
closes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/253
closes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/365

Add requirements for Docker Desktop.

---

project-docs/release-notes/version-2.7.1.md
workshop-images/base-environment/opt/renderer/src/frontend/scripts/educates.ts

fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/388

Fix cascade for clickable actions when followed by text.

---

project-docs/release-notes/version-2.7.1.md
secrets-manager/handlers/helpers.py
secrets-manager/handlers/namespace.py
secrets-manager/handlers/secret.py
secrets-manager/handlers/secretcopier.py
secrets-manager/handlers/secretcopier_funcs.py
secrets-manager/handlers/secretexporter.py
secrets-manager/handlers/secretimporter.py
secrets-manager/handlers/secretinjector.py
secrets-manager/handlers/secretinjector_funcs.py
secrets-manager/handlers/serviceaccount.py
secrets-manager/main.py
session-manager/handlers/analytics.py
session-manager/handlers/daemons.py
session-manager/handlers/trainingportal.py
session-manager/handlers/workshopallocation.py
session-manager/handlers/workshopenvironment.py
session-manager/handlers/workshopsession.py
session-manager/main.py
training-portal/bin/start-container
training-portal/src/httpd.conf
training-portal/src/project/apps/workshops/manager/analytics.py
training-portal/src/project/apps/workshops/manager/cleanup.py
training-portal/src/project/apps/workshops/manager/environments.py
training-portal/src/project/apps/workshops/manager/operator.py
training-portal/src/project/apps/workshops/manager/portal.py
training-portal/src/project/apps/workshops/manager/sessions.py
training-portal/src/project/wsgi.py

fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/395
fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/394
fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/393

Logging improvements and other fixes.

---

project-docs/release-notes/version-2.7.1.md
workshop-images/base-environment/opt/gateway/package-lock.json
workshop-images/base-environment/opt/gateway/package.json
workshop-images/base-environment/opt/gateway/src/backend/modules/assets.ts
workshop-images/base-environment/opt/gateway/src/frontend/scripts/educates.ts

fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/374

Update xterm.js and fix clickable terminal links.

---

project-docs/release-notes/version-2.7.1.md
project-docs/workshop-content/workshop-instructions.md
workshop-images/base-environment/opt/renderer/src/frontend/scripts/educates.ts

closes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/398

Allow cooldown period to be overridden for clickable actions.

---

developer-docs/build-instructions.md

closes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/408

Developer docs updates.

---

carvel-packages/installer/bundle/config/ytt/_ytt_lib/config/save-config-overlay.yaml

Fixing bug in configmap format

---

client-programs/pkg/installer/installer.go

Adding version=latest will use local registry and 0.0.1 version for development UX simplicity.
Closes #416

Version latest

---

project-docs/release-notes/version-3.0.0.md
training-portal/src/httpd.conf
training-portal/src/project/apps/workshops/admin.py
training-portal/src/project/apps/workshops/manager/environments.py
training-portal/src/project/apps/workshops/manager/portal.py

fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/435
fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/434

Fix issues with workshop environments stuck in STARTING state.

---

project-docs/index.rst
project-docs/release-notes/version-2.7.2.md
training-portal/src/httpd.conf
training-portal/src/project/apps/workshops/admin.py
training-portal/src/project/apps/workshops/manager/environments.py
training-portal/src/project/apps/workshops/manager/portal.py

Back port of fixes related to workshop environments getting stuck in STARTING state.
* https://github.com/vmware-tanzu-labs/educates-training-platform/issues/434
* https://github.com/vmware-tanzu-labs/educates-training-platform/issues/435

Backport fixes for workshop environment state getting stuck.

---

project-docs/release-notes/version-3.0.0.md
training-portal/src/project/apps/workshops/templates/workshops/catalog.html
training-portal/src/project/static/styles/project.css
training-portal/src/project/templates/project-base.html

fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/439

Training portal theme not applying to access control pages.

---

project-docs/conf.py
project-docs/custom-resources/workshop-definition.md
project-docs/release-notes/version-3.0.0.md
project-docs/requirements.txt
session-manager/handlers/application_git.py
session-manager/handlers/helpers.py
session-manager/handlers/workshopsession.py
workshop-images/base-environment/opt/eduk8s/etc/templates/workshop-variables.yaml
workshop-images/base-environment/opt/gateway/src/backend/modules/config.ts
workshop-images/base-environment/opt/gateway/src/backend/modules/proxy.ts
workshop-images/base-environment/opt/renderer/src/backend/modules/config.ts

closes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/444
Also adds copy icon functionality to code blocks in docs.

Basic auth tokens for registry and git services.

---

docker-extension/ui/package-lock.json
workshop-images/base-environment/opt/gateway/package-lock.json
workshop-images/base-environment/opt/gateway/package.json

closes https://github.com/vmware-tanzu-labs/educates-training-platform/pull/451
closes https://github.com/vmware-tanzu-labs/educates-training-platform/pull/450

Update packages due to CVEs.

---

project-docs/index.rst
project-docs/installation-guides/carvel-based-installation.md
project-docs/installation-guides/cli-based-installation.md
project-docs/installation-guides/infrastructure-providers.md
project-docs/installation-guides/installation-instructions.md

First pass at docs updates. Not yet complete as need to change GitHub actions to create more release assets to make process easier.

Updates for new installation process.

---

carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/cert-manager/upstream/cert-manager.yaml
carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/contour/upstream/02-job-certgen.yaml
carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/contour/upstream/03-contour.yaml
carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/contour/upstream/03-envoy.yaml
vendir.lock.yml
vendir.yml

Upgrade those 2 components to the latest patches on current minor versions.
Tested locally.
No issue has been created for this PR

Updated contour and cert-manager to latest patches

---

carvel-packages/installer/bundle/config/ytt/_ytt_lib/infrastructure/custom/educates.lib.yaml
carvel-packages/installer/bundle/config/ytt/_ytt_lib/infrastructure/eks/educates.lib.yaml
carvel-packages/installer/bundle/config/ytt/_ytt_lib/infrastructure/generic/educates.lib.yaml
carvel-packages/installer/bundle/config/ytt/_ytt_lib/infrastructure/gke/educates.lib.yaml
carvel-packages/installer/bundle/config/ytt/_ytt_lib/infrastructure/kind/educates.lib.yaml
carvel-packages/installer/bundle/config/ytt/_ytt_lib/infrastructure/vcluster/educates.lib.yaml
session-manager/handlers/workshopallocation.py
session-manager/handlers/workshopenvironment.py
session-manager/handlers/workshopsession.py

fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/473
Also adds analytics reporting for resource errors as noted in https://github.com/vmware-tanzu-labs/educates-training-platform/issues/472

Analytics reporting

---

Makefile

fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/476

Deletion using kapp needs to use label identification.

---

carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/educates/10-secrets-manager/07-deployments.yaml
carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/educates/11-session-manager/07-deployments.yaml

fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/475

Increase startup/liveness probe timeouts and periods.

---

client-programs/pkg/installer/installer.go

Deletes `educates-installer` namespace creation/deletion code that was there from the time when educates platform was installed via a kapp App that was not relying on labeling the resources. Now, this namespace is no longer needed.
Closes #480

Removing educates-installer ns from CLI commands

---

Makefile
carvel-packages/installer/README.md

Removing educates namespace installer
No issue related

Remove educates-installer ns

---

secrets-manager/handlers/secretcopier_funcs.py
session-manager/handlers/daemons.py
session-manager/handlers/workshoprequest.py
session-manager/handlers/workshopsession.py

fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/490

Fix exception handling

---

client-programs/pkg/cmd/admin_platform_deploy_cmd.go

Since there is a `educates admin platform delete` command, there's no need to have the `--delete` flag anymore on the `deploy` command

Removing delete option on platform deploy command

---

Makefile
project-docs/custom-resources/workshop-definition.md
project-docs/getting-started/quick-start-guide.md
project-docs/getting-started/sample-workshops.md

Sample Kubernetes workshop was moved.

Update sample workshop location.

---

workshop-images/base-environment/opt/gateway/package-lock.json
workshop-images/base-environment/opt/gateway/package.json

closes https://github.com/vmware-tanzu-labs/educates-training-platform/security/dependabot/162

Update requirejs version due to CVE.

---

project-docs/installation-guides/carvel-based-installation.md
training-portal/src/project/apps/workshops/views/session.py

fixes https://github.com/vmware-tanzu-labs/educates-training-platform/issues/522
Also minor doc fix.

Session user tracking.

---

project-docs/getting-started/quick-start-guide.md

Add Colima details based on #447
Fix #447

docs: add colima details to quick-start-guide

---

carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/educates/_ytt_lib/lookup-service/upstream/crd-clientconfig.yaml
lookup-service/service/caches/clients.py
lookup-service/service/caches/clusters.py
lookup-service/service/caches/databases.py
lookup-service/service/caches/environments.py
lookup-service/service/caches/portals.py
lookup-service/service/handlers/clients.py
lookup-service/service/handlers/clusters.py
lookup-service/service/routes/authnz.py
lookup-service/service/routes/clients.py
lookup-service/service/routes/workshops.py

Fixes response codes, labels, and adds user binding and user logout.

Lookup service fixes.

---

project-docs/workshop-content/workshop-instructions.md

Updates docs on examiner input values.

---

client-programs/pkg/cmd/cluster_portal_create_cmd.go
project-docs/index.rst
project-docs/release-notes/version-3.2.0.md

Allow override of hostname when creating portal using CLI.

---

client-programs/pkg/cmd/cluster_portal_create_cmd.go
project-docs/release-notes/version-3.2.0.md

Add ability to set default image repository for a training portal using CLI.

---

carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/educates/11-session-manager/01-crds-workshop.yaml
project-docs/release-notes/version-3.2.0.md
workshop-images/base-environment/opt/gateway/src/backend/modules/proxy.ts
workshop-images/base-environment/opt/helper/src/extension.ts

fixes https://github.com/educates/educates-training-platform/issues/637
fixes https://github.com/educates/educates-training-platform/issues/638

Gateway session proxy.

---

session-manager/handlers/workshopenvironment.py

Fix up injection of environment data variables.

---

docker-extension/Dockerfile

Update to Debian bookworm base image.

---

docker-extension/Makefile

Fix installation of local docker extension.

---

project-docs/index.rst
project-docs/release-notes/version-3.2.1.md
workshop-images/base-environment/Dockerfile

closes https://github.com/educates/educates-training-platform/issues/641
closes https://github.com/educates/educates-training-platform/issues/642

Package updates.

---

carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/educates/08-lookup.yaml
carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/educates/_ytt_lib/lookup-service/overlays.yaml/overlay-ingress.yaml
carvel-packages/installer/bundle/config/ytt/_ytt_lib/packages/educates/_ytt_lib/values-schema.yaml
session-manager/handlers/trainingportal.py
session-manager/handlers/workshopsession.py

fixes https://github.com/educates/educates-training-platform/issues/674
fixes https://github.com/educates/educates-training-platform/issues/553
fixes https://github.com/educates/educates-training-platform/issues/549

Ingress fixes.

---

project-docs/release-notes/version-3.2.1.md
session-manager/handlers/workshopallocation.py
session-manager/handlers/workshopenvironment.py
session-manager/handlers/workshopsession.py

fixes https://github.com/educates/educates-training-platform/issues/583

Carvel secrets blocking

---

client-programs/pkg/config/installationconfig.go
go.work.sum
project-docs/release-notes/version-3.2.1.md

fixes https://github.com/educates/educates-training-platform/issues/680

Wrong naming for blockCIDRs.

---

project-docs/release-notes/version-3.2.1.md
training-portal/src/project/apps/workshops/views/environment.py

closes https://github.com/educates/educates-training-platform/issues/649

REST API restrictions on workshop creation.

---

client-programs/pkg/cmd/docker_workshop_deploy_cmd.go
project-docs/release-notes/version-3.3.0.md

fixes https://github.com/educates/educates-training-platform/issues/698

Fix workshop deployment to local docker environment.

---

lookup-service/service/caches/portals.py

fixes https://github.com/educates/educates-training-platform/issues/700

Be more resilient to errors when calling training portals.

---

lookup-service/service/caches/environments.py
lookup-service/service/caches/portals.py
lookup-service/service/routes/workshops.py
project-docs/release-notes/version-3.3.0.md

closes https://github.com/educates/educates-training-platform/issues/703

Add ability to specify user info when using lookup service.

---

client-programs/pkg/diagnostics/fetcher.go

closes https://github.com/educates/educates-training-platform/issues/714

Add timestamps to collected logs.

---

.github/ISSUE_TEMPLATE/adopter.yml
ADOPTERS.md
README.md

Adding support for registering adopters

---

ADOPTERS.md

NETWAYS Managed Services relies on Educates for its public playground, internal training environments for teams across the NETWAYS group, and on-demand workshops at meetups and conferences.

Add NETWAYS to the ADOPTERS.md file

---

ADOPTERS.md

Added 12F aps to the list of adopters

added 12f aps

---

session-manager/handlers/workshopsession.py

The `args` list of the `docker` container within a workshop session was formatted in a way that would pass the following `dockerd` flags to `/bin/sh` instead to `dockerd`:
- `--insecure-registry`
- `--registry-mirror`
Thus, the [Image Registry Pull Through Cache feature](https://docs.educates.dev/en/stable/installation-guides/configuration-settings.html#image-registry-pull-through-cache) didn't work as expected.
Now, `dockerd` args get collected and compiled into a list before injecting them into the container's `args` list.
Discussion on the Kubernetes Slack: [Thread](https://kubernetes.slack.com/archives/C05UWT4SKRV/p1746428214199219)

Fix cache config in session docker sidecar

---

training-portal/src/project/apps/workshops/admin.py

closes https://github.com/educates/educates-training-platform/issues/734

Display seconds in timestamps of admin pages.
